---
- hosts: desktop
  become: true
  tasks:
  - name: Add the flathub flatpak repository.
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
      method: system

  - name: Add the flathub-beta flatpak repository.
    community.general.flatpak_remote:
      name: flathub-beta
      state: present
      flatpakrepo_url: https://flathub.org/beta-repo/flathub-beta.flatpakrepo
      method: system

  - name: Install Flatpaks 
    community.general.flatpak:
      name: 
      - com.mattjakeman.ExtensionManager
      - org.gnome.seahorse.Application
      - com.valvesoftware.Steam
      - net.davidotek.pupgui2
      - org.mozilla.firefox
      - com.wps.Office
      - org.gnome.Meld
      - com.prusa3d.PrusaSlicer
      - org.gnome.DejaDup
      - org.gnome.World.PikaBackup
      - org.signal.Signal
      - com.discordapp.Discord
      # lutris
      - org.gnome.Platform.Compat.i386/x86_64/41
      - org.freedesktop.Platform.GL32.default/x86_64/21.08
      - org.freedesktop.Platform.GL.default/x86_64/21.08
      state: present
      method: system

  - name: Install Flatpak-betas 
    community.general.flatpak:
      remote: flathub-beta
      name: 
        # lutris
        - net.lutris.Lutris
      state: present
      method: system
    