name: Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Wireguard VPN through Tailscale
        # or use main branch to go on the bleeding edge
        uses: MadeByThePinsHub/tailscale-action-labels@v0.1.0
        with:
          # secret name may varies on your org
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          # the defaults tag goes here, plus some addons.
          labels: ${{ secrets.TAG }}
          # Going to unstable is risky, beware!
          version: "1.21.120"
      
      - name: check connection
        run: tailscale ip -4 ${{ secrets.HOST }} > /dev/null && tailscale ip -6 ${{ secrets.HOST }} > /dev/null
          
      - name: Add SSH key
        id: ssh
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          MACHINE_IP=$(tailscale ip -4 ${{ secrets.HOST }})
          ssh-keyscan $MACHINE_IP >> ~/.ssh/known_hosts
          printf "%s" "$SSH_KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key

      - name: Deploy code to server
        id: deploy
        run: |
          MACHINE_IP=$(tailscale ip -4)
          ssh -i ~/.ssh/key "${{ secrets.USERNAME }}@$MACHINE_IP" "touch test && exit"


