name: CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Install libnotify
      #   run: sudo apt-get install libnotify-bin

      - name: Setup Tailscale
        # or use main branch to go on the bleeding edge
        uses: tailscale/github-action@v1
        with:
          # secret name may varies on your org
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          # # the defaults tag goes here, plus some addons.
          # labels: tag:gh-actions
          # # Going to unstable is risky, beware!
          # version: "1.22.0"
          
      - name: Update Tailscale Tags
        run: sudo tailscale up --advertise-tags=${{ secrets.TAG }} --accept-routes --hostname="github-$(cat /etc/hostname)"
      
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: whoami