name: Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Wireguard VPN through Tailscale
        env:
          AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
          TAG: ${{ secrets.TAG }}
        run: |
          sudo curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscaled 2>~/tailscaled.log &
          HOSTNAME="gh-actions"
          until sudo tailscale up --authkey ${AUTHKEY} --hostname ${HOSTNAME} --advertise-tags ${TAG} --accept-routes
          do
            echo "warning: Tailnet Wireguard tunnel still not ready, please standby..."
            sleep 0.5
          done
          echo "Successfully connected to tailnet!"

      - name: install ansible
        id: ansible
        run: | 
          sudo apt-get install software-properties-common
          sudo apt-add-repository ppa:ansible/ansible
          sudo apt-get update
          sudo apt-get install ansible

      - name: check connection
        id: connect
        env:
          HOST: ${{ secrets.HOST }}
        run: tailscale ip -4 $HOST > /dev/null && tailscale ip -6  $HOST > /dev/null
          
      - name: Add SSH key
        id: ssh
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          HOST: ${{ secrets.HOST }}
        run: |
          KEY_PATH=./key
          mkdir -p ~/.ssh
          MACHINE_IP=$(tailscale ip -4 $HOST)
          ssh-keyscan $MACHINE_IP >> ~/.ssh/known_hosts
          printf "%s" "$SSH_KEY" > $KEY_PATH
          chmod 600 $KEY_PATH

      - name: Deploy code to server
        id: deploy
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USERNAME }}
        run: |
          pwd
          ls
          ansible all -m ping
          
          # MACHINE_IP=$(tailscale ip -4 $HOST )
          # ssh -i $KEY_PATH "${USER}@${MACHINE_IP}" "touch test && exit"


